Score cluster
NYCUarchery/archeryWebsite pull request #142
Opened 2024-09-02 14:37 UTC by Mushroom-MSL1L

1. new api that update end score in a api 
2. reformat the config files

2024-09-02 14:39 UTC, Mushroom-MSL1L commented
@Otmeal 如果issue解決可以順便幫我關了嗎

2024-09-02 23:46 UTC, Otmeal requested changes
🅿️

2024-09-02 23:46 UTC, Otmeal commented on backend/docs/docs.go
> +        "/api/player/allendscores/{id}": {
這種多字的URL片段應該要分開來，用Kebab Case或延續之前的風格。

2024-09-02 23:46 UTC, Otmeal commented on backend/docs/docs.go
> +	BasePath:         "/",
我覺得應該保持這個`/api/`比較好，畢竟前端在用的時候，前面確實都會掛一個`/api/`。之後要把其他的`/api/`前墜清掉。

2024-09-02 23:46 UTC, Otmeal commented on backend/internal/endpoint/Player.go
> +func UpdatePlayerTotalScore(context *gin.Context, playerId uint) {
我在想改成Refresh之類的會不會比較好，Update有點誤導性。

2024-09-02 23:46 UTC, Otmeal commented on backend/main.go
> +//	@BasePath  /
這個根據上面的也要改回去。

2024-09-03 11:16 UTC, Otmeal approved these changes
@Mushroom-MSL1L @Bennybenny124 要不要協調一下，這包有動到swagger的部分，怕到時候benny做完太多conflict。

2024-09-03 12:00 UTC, Mushroom-MSL1L commented
> @Mushroom-MSL1L @Bennybenny124 要不要協調一下，這包有動到swagger的部分，怕到時候benny做完太多conflict。

這branch合進去dev 之後 ，@Bennybenny124 的branch在和dev 整合一下囉

2024-09-03 12:17 UTC, Otmeal approved these changes

2024-09-03 12:18 UTC, merged