No Institution
NYCUarchery/archeryWebsite pull request #210
Opened 2024-11-02 17:19 UTC by Bennybenny124

1. Creates NoInstitution upon database setup
2. Ensures the existence and uniqueness of NoInstitution
3. Disables deletion of NoInstitution
4. Handles moving users to NoInstitution when an institution is deleted
5. Integrates NoInstitution logics with seeder function

May require further testings. @Otmeal please help!

2024-11-03 17:11 UTC, Mushroom-MSL1L reviewed
1. 可以再精簡，刪。
2. 有些東西不要commit上來。
3. 不同issue的請分開。

內文有更多review

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/main.go
> -//	@host	127.0.0.1:80
這不應該被commit上來。

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/internal/endpoint/user.go
> +	}
這是另一個issue的工作
#167

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/internal/endpoint/institution.go
> +	database.MoveUsersToNoInstitutionByInstitutionID(uint(id))
MoveUsersToNoInstitutionByInstitutionID 有return error ，最好接一下。
可以善用 pkg.error 相關的函式，message會是格式化的，程式也比較少。

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/internal/database/NoInstitution.go
> +var NoInstitutionID uint = 1
痾，變數放一起比較直觀？
這我不確定。

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/internal/database/DB.go
> +func setInitialDataWithSeeder() {
確定功能重複或沒用到的扣就刪了背唄。

2024-11-03 17:11 UTC, Mushroom-MSL1L commented on backend/assets/seeder/initData.sql
> +INSERT INTO `institutions` VALUES (1,'No Institution');
用途重複就刪了唄。

2024-11-03 17:13 UTC, Mushroom-MSL1L requested changes
卡

2024-11-04 13:12 UTC, Bennybenny124 commented on backend/internal/database/DB.go
> +func setInitialDataWithSeeder() {
目前的做法是當mode是test的時候保留直接insert的寫法，否則使用CreateNoInstitution。
因為目前只在測試模式的時候才有大量資料需要塞進去，保留為了是避免以後有在正常模式也需要塞大量資料的情形發生(例：資料庫搬家？我不太確定)。
現在這兩個寫法間(貌似)是相容的。

2024-11-04 13:12 UTC, Bennybenny124 commented on backend/assets/seeder/initData.sql
> +INSERT INTO `institutions` VALUES (1,'No Institution');
同上

2024-11-04 13:15 UTC, Bennybenny124 commented on backend/main.go
> -//	@host	127.0.0.1:80
改swag init 的時候自己動到的？
commit前要手動檢查嗎？還是有其他方法？？

2024-11-04 13:17 UTC, Bennybenny124 commented on backend/internal/database/NoInstitution.go
> +var NoInstitutionID uint = 1
ㄟ 放下面是因為他的預設值基本上沒有意義？
他有點像Create No Institution 的output.

2024-11-04 14:27 UTC, Mushroom-MSL1L commented on backend/main.go
> -//	@host	127.0.0.1:80
gitignore 或人工檢查。
看你的判斷。

2024-11-04 14:32 UTC, Mushroom-MSL1L commented on backend/internal/database/DB.go
> +func setInitialDataWithSeeder() {
但這個函式和原本test mode 的DummyData沒有相關啊。
然後dev mode也已經會用另一種方式跑no institution了誒。

2024-11-04 14:33 UTC, Mushroom-MSL1L commented on backend/internal/database/NoInstitution.go
> +var NoInstitutionID uint = 1
什麼意思？？

2024-11-05 06:57 UTC, Bennybenny124 commented on backend/main.go
> -//	@host	127.0.0.1:80
凹嗚

2024-11-05 07:05 UTC, Bennybenny124 commented on backend/internal/database/DB.go
> +func setInitialDataWithSeeder() {
就是說之後如果需要在dev mode 的資料庫裡塞資料(像現在test mode會做的事情)，
這個函式還有initData.sql就會派上用場。
到時候只要修改initData.sql然後在DatabaseInitial()裡面，
把CreateNoInstitution()註解掉，改成setInitialDataWithSeeder()就可以了。

2024-11-05 07:12 UTC, Bennybenny124 commented on backend/internal/database/NoInstitution.go
> +var NoInstitutionID uint = 1
呼叫CreateNoInstitution()之後這個變數就會被修改，儲存No Institution的ID，
所以其實不初始化也沒關係，反正馬上會被改掉，現在初始化 = 1是為了相容seeder。
也就是說這個變數基本上不需要被修改，我就把他放在後面了。
嘛 但是放前面好像也不錯啦。

2024-11-08 16:51 UTC, Mushroom-MSL1L commented on backend/main.go
> -//	@host	127.0.0.1:80
所以刪了嗎

2024-11-08 16:53 UTC, Mushroom-MSL1L commented on backend/internal/database/DB.go
> +func setInitialDataWithSeeder() {
不要用註解啦😠

2024-11-09 14:37 UTC, Mushroom-MSL1L reviewed
11/9：好棒，明天我測

2024-11-09 14:37 UTC, Bennybenny124 commented
#166 
#209

2024-11-15 06:38 UTC, Mushroom-MSL1L approved these changes
@Bennybenny124 好棒
#167

2024-11-16 12:25 UTC, merged