"Scoring system with player before merge"
NYCUarchery/archeryWebsite pull request #47
Opened 2023-11-16 07:18 UTC by Mushroom-MSL1L

1. request merge "Scoring system with player before merge" branch into "dev"
2. this branch has already merge "dev" into branch of "scoring_system" (hope these's no confilct)
3. have functions about player
4. change url to "api" prefix
5. merge files in "translate" path into files in "endpoint" path
** hope Jason at least review the part about router, participant, user**

2023-11-16 12:11 UTC, JasonTuTW approved these changes

2023-11-16 15:30 UTC, lolainta requested changes
- Do not commit unrelated files, such as archery_game_scoring folder.
- Make sure that all files are up to date with dev branch. (README.md are modified)

2023-11-16 15:30 UTC, lolainta commented on go.work
> +use ./backend
We don't need `go.work` and `go.work.sum`

2023-11-16 15:30 UTC, lolainta commented on .gitignore
> +
Not needed

2023-11-18 03:46 UTC, lolainta approved these changes

2023-11-18 03:46 UTC, lolainta commented on .gitignore
This file is needed

2023-11-18 05:00 UTC, Mushroom-MSL1L commented on .gitignore
> +
Did I misunderstand?
You just want to delete a blank line, right?

2023-11-18 12:12 UTC, lolainta approved these changes

2023-11-18 12:12 UTC, merged